### ISSUE TITLE
Example: Creating Transactions Over Time

### ISSUE THREAD

**Issue by kvdecvlt** [cameo-engineering/tonconnect#3]
Hello, in the basic example, we establish a connection and then create a transaction. However, there's a lack of examples where the connection has already been established and the list of wallets has been saved, and where we need to create a transaction at a later time upon request. Could you provide an example similar to this official example? https://github.com/yungwine/ton-connect-bot/blob/main/src/main.py#L33

**Comment by denisplayhub** [comment]
I guess it doesn't support storing/restoring sessions like the. original JS/Python SDK.

**Comment by gulitsky** [comment]
https://github.com/cameo-engineering/tonconnect/issues/4#issuecomment-2230808184
