### ISSUE TITLE
Session store/restore functionality.

### ISSUE THREAD

**Issue by sadensmol** [cameo-engineering/tonconnect#4]
Hi @gulitsky 
Do you have any further plans to improve and support this project? 
I'm looking for session store/restore functionality.
Thank you.

**Comment by gulitsky** [comment]
I'm not in favor of the high-level opaque approach to interacting with sessions in `@ton-connect/sdk`, it doesn't lay well with Go philosophy. But there are already JSON tags in the Session structure, so you can do `json.Marshal` / `json.Unmarshal` and use whatever session storage (plain file, database, KV storage) you like. 
The only thing I completely forgot to do is to add a `Restore` method that will restore the connection from an already unmarshaled session. I think I'll add this method and example in the next day or two.

**Comment by sadensmol** [comment]
Thank you so much! Looking forward to it!

**Comment by sadensmol** [comment]
Hi @gulitsky . 
Maybe you need some help on this problem? 
I'm not sure I know where to start from - but this restore functionality is essential. Not only restoring deserialized session, but also restoring wallet gateway on the wallet's side!
I'm still missing this so much!!! 
Thank you!

**Comment by gulitsky** [comment]
> Hi @gulitsky . Maybe you need some help on this problem? I'm not sure I know where to start from - but this restore functionality is essential. Not only restoring deserialized session, but also restoring wallet gateway on the wallet's side! I'm still missing this so much!!! Thank you!

Hi, just added session persistence to the [example](https://github.com/cameo-engineering/tonconnect/blob/master/examples/basic/main.go). Some minor bugs have also been fixed and the wallet list has been updated.
