### ISSUE TITLE
Session still connected

### ISSUE THREAD

**Issue by maxim-panchuk** [cameo-engineering/tonconnect#6]
How to check if session is still connected? I mean that user didn't close the connection from his wallet to the app?

**Comment by gulitsky** [comment]
When the user disables the application in their wallet, a ["Disconnect" message](https://docs.ton.org/develop/dapps/ton-connect/protocol/requests-responses#wallet-events) is sent. To handle it, it is necessary to continuously listen to the session, which this (and, AFAIK, not even the official one) library does not do.
